try {
    let a;
    console.log(a.length);
} catch (error){
    console.log("Hi there");
}

// In case there is exception then the control goes over to the exception
